#if !canImport(ObjectiveC)
import XCTest

extension CSDL2Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CSDL2Tests = [
        ("testVersion", testVersion)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CSDL2Tests.__allTests__CSDL2Tests)
    ]
}
#endif
