name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ["12.4"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Restore cached Homebrew dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/Homebrew/sdl2--*
            ~/Library/Caches/Homebrew/downloads/*--sdl2-*
          key: ${{ runner.os }}-brew-sdl2-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: ${{ runner.os }}-brew-sdl2-
      - name: Restore cached SPM dependencies
        uses: actions/cache@v2
        with:
          path: |
            .build/repositories
          key: ${{ runner.os }}-spm-repos-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-repos-
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Install dependencies
        run: |
          brew install sdl2
          sdl2-config --version
      - name: Test
        run: make test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Build Release
        run: make build-release
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Restore APT cache
        uses: actions/cache@v2
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt
      - name: Restore cached SPM dependencies
        uses: actions/cache@v2
        with:
          path: |
            .build/repositories
          key: ${{ runner.os }}-spm-repos-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-repos-
      - name: Install dependencies
        run: |
          apt update
          apt-get install -y libsdl2-dev
          sdl2-config --version
      - name: Test
        run: make test
      - name: Build Release
        run: make build-release
